config/routes.rb
Rails.application.routes.draw do
  resources :videos do
  	collection do 
  		get :disliked
 		get :liked
 		get :myvideo
 	  	get :tag
 	end
 	member do
  		resources :comments, only: :create
  	end
  end
  devise_for :users ,:controllers => { :omniauth_callbacks => "omniauth_callbacks" } 

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'videos#index'
end

app/models/video.rb
class Video < ApplicationRecord
  has_and_belongs_to_many :tags ,class_name: "Tag"
  belongs_to :uploader,class_name: "User"
  has_many :likes
  has_many :dislikes
  has_many :comments
  has_many :views
  mount_uploaders :preview_images,PreviewImagesUploader
  mount_uploader :movie, VideoUploader
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  before_action :set_video, only: [:show, :edit, :update, :destroy]

  # GET /videos
  # GET /videos.json

  def index
    @videos = Video.where(published: true)
  end

  # GET /videos/1
  # GET /videos/1.json
  def show
    @comments = Video.find(params[:id]).comments.where(comments_id: nil)
    @comment = Comment.new
    @likes = Like.find_by_video_id(params[:id]).count
    @likes = Dislike.find_by_video_id(params[:id]).count
  end

  # GET /videos/new
  def new
    @tags = Tag.all
    @taghash = Hash.new
    for i in @tags
      @taghash["#{i.name}"] = nil;
    end
    @taghashj = @taghash.to_json
    @video = Video.new
  end

  # GET /videos/1/edit
  def edit
    @id = params[:id]
    @video = Video.find(@id)
    @stag = @video.tags
    br = Array.new
    for i in @stag
      br.push("#{i.name}")
    end
    @savedTag = br
    @tags = Tag.all
    @taghash = Hash.new
    for i in @tags
      @taghash["#{i.name}"] = nil;
    end
    @taghashj = @taghash.to_json
    @tag_name = @video.tag_name
  end

  # POST /videos
  # POST /videos.json
  def create
    video_params["tag_name"][0]=""
    ar = video_params["tag_name"].split(",")
    ar.delete("")
    for i in ar
      i.capitalize!
    end
    @video = Video.new(video_params)
    @video.uploader = current_user
    @video.count = 0
    for i in ar
      @s = Tag.find_by_name(i)
      if(@s.nil? == true)
        @newTag = Tag.new(:name => i ,:occurence => 1)
        @newTag.save
        @video.tags << @newTag
      else
        count = @s.occurence
        @s.occurence = count + 1
        @s.save
        @video.tags << @s
      end
    end
    respond_to do |format|
      if @video.save
        format.html { redirect_to @video, notice: 'Video was successfully created.' }
        format.json { render :show, status: :created, location: @video }
      else
        format.html { render :new }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /videos/1
  # PATCH/PUT /videos/1.json
  def update
    previous = @video.tag_name.split(",")
    current = video_params["tag_name"].split(",") - [""]
    deleted = previous - current
    newadded = current - previous
    binding.pry
    for i in deleted
      b = Tag.find_by_name(i)
      @video.tags.delete(b)
      c = b.occurence
      b.occurence = c - 1
      b.save
    end
    for i in newadded
      i.capitalize!
    end
    for i in newadded
      @s = Tag.find_by_name(i)
        if(@s.nil? == true)
          @newTag = Tag.new(:name => i ,:occurence => 1)
          @newTag.save
          @video.tags << @newTag
        else
          if(@video.tags.include? @s)
            
          else
            count = @s.occurence
            @s.occurence = count + 1
            @s.save
            @video.tags << @s
          end
        end
    end
    respond_to do |format|
      if @video.update(video_params)
        format.html { redirect_to @video, notice: 'Video was successfully updated.' }
        format.json { render :show, status: :ok, location: @video }
      else
        format.html { render :edit }
        format.json { render json: @video.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /videos/1
  # DELETE /videos/1.json
  def destroy
    @video.destroy
    respond_to do |format|
      format.html { redirect_to videos_url, notice: 'Video was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def liked

  end

  def disliked

  end
  
  def myvideo 
    @videos = Video.where(uploader: current_user)
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_video
      @video = Video.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def video_params
      params.require(:video).permit(:title, :description, :uploader_id, :published,:movie,:tag_name,{preview_images: []}, tag_ids: [])
    end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_comment.html.erb
<h2>COMMENTS</h2>
<hr>
<% @comments.each do |comment| %>
<ul class="collapsible" data-collapsible="accordion">
    <li>
      <div class="collapsible-header" style="height:10%;">
      	<%= image_tag User.find(comment.commentor_id).profile_picture ,class: "circle" %>
      	<br>
      	&nbsp;&nbsp;
      	<%= [User.find(comment.commentor_id).first_name,User.find(comment.commentor_id).last_name].join(" ")%>
      	<br>
      	&nbsp;&nbsp;
      	<%= comment.body%>
      <i class="material-icons medium">reply</i>      
      </div>
      <div class="collapsible-body">
      	<span>
      		<ul class="collection">
		    <% comment.replies.each do |reply| %>
			    <li class="collection-item avatar">
			      		<%= image_tag User.find(reply.commentor_id).profile_picture ,class: "circle" %>
			      <span class="title"><%= [User.find(reply.commentor_id).first_name,User.find(reply.commentor_id).last_name].join(" ")%></span>
			      <p>
			      	<%= reply.body%><br>
			      </p>
			    </li>
			   <% end %>
			   <%= simple_form_for(@comment, remote: true) do |f| %>
				<%= f.error_notification %>
			  	<div class="form-inputs">
			  	  <%= f.hidden_field :comments_id , value: comment.id%>
			  	  <%= f.text_field :body, label: false,placeholder: "Add a Reply" %>
			  	</div>
			  	<div class="form-actions">
			   	  <%= f.button :submit ,value: "Reply" %>
			  	</div>
			  <%end %>		
      	</span>
      </div>
    </li>
  </ul>
 <% end %>
<%= simple_form_for(@comment, remote: true) do |f| %>
<%= f.error_notification %>
  	<div class="form-inputs">
  	  <%= f.text_field :body, label: false ,placeholder: "Add a Comment" %>
  	</div>
  	<div class="form-actions">
   	  <%= f.button :submit ,value: "Comment" %>
  	</div>
 <%end %>
 <script>
  $('.collapsible').collapsible({
    accordion: true, // A setting that changes the collapsible behavior to expandable instead of the default accordion style
    onOpen: function(el) {  }, // Callback for Collapsible open
    onClose: function(el) {  } // Callback for Collapsible close
  });
</script>

app/views/videos/_form.html.erb
<%= simple_form_for(@video,remote: true) do |form| %>
  <% if video.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(video.errors.count, "error") %> prohibited this video from being saved:</h2>
      <ul>
      <% video.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-inputs"> 
    <%= form.hidden_field :tag_name, value: "" ,id: :tag_name%>
    <%= form.input :title, id: :video_title %>
    <div class="row">
        <div class="input-field col s12">
          <textarea id="textarea1" name="video[description]" class="materialize-textarea"></textarea>
      <label for="textarea1">Description</label>
        </div>
    </div>
    <label for="spaceTags">Tags</label>
    <div id="spaceTags" class="chips chips-placeholder">
    </div>
    <%= form.label :movie %>
    <%= form.file_field :movie %>
    <%= form.label :preview_images%>
    <%= form.file_field :preview_images, multiple: true %>
    <p>
      <input type="checkbox" name=video[published] id="test5" />
      <label for="test5">Publish Video</label>
    </p>
  <div class="form-actions">
    <%= form.submit%>
  </div>
<% end %>
<script type="text/javascript">
  $('#textarea1').trigger('autoresize');
  $('.chips').material_chip();
  $('.chips-placeholder').material_chip({
    placeholder: 'Enter a tag',
    secondaryPlaceholder: '+Tag',
    autocompleteOptions: {
      data:  <%=raw(@taghashj)%>,
      limit: Infinity,
      minLength: 1
    }
  });
  $('.chips').on('chip.add', function(e, chip){
    var b = document.getElementById("tag_name").value
    b = b +","+ chip["tag"];
    document.getElementById("tag_name").value = b;
    });
</script>

app/views/videos/disliked.html.erb
<h1>
	DISLIKED VIDEOS
</h1>

app/views/videos/edit.html.erb
<h1>Editing Video</h1>
<%= simple_form_for(@video) do |form| %>
<div class="form-inputs"> 
    <%= form.hidden_field :tag_name, value: raw(@tag_name) ,id: :tag_name%>
    <%= form.input :title, id: :video_title %>
    <div class="row">
        <div class="input-field col s12">
          <textarea id="textarea1" name="video[description]" class="materialize-textarea"></textarea>
      <label for="textarea1">Description</label>
        </div>
    </div>
    <label for="spaceTags">Tags</label>
    <div id="spaceTags" class="chips chips-placeholder">
    </div>
    <p>
      <input type="checkbox" name=video[published] id="test5" />
      <label for="test5">Publish Video</label>
    </p>
  <div class="form-actions">
    <%= form.submit%>
  </div>
<% end %>
<script type="text/javascript">
  $('#textarea1').trigger('autoresize');
  $('.chips').material_chip();
  $('.chips-placeholder').material_chip({
    placeholder: 'Enter a tag',
    secondaryPlaceholder: '+Tag',
    autocompleteOptions: {
      data: <%= raw(@taghashj) %>,
      limit: Infinity,
      minLength: 1
    },
    data: [
      <% for i in @savedTag%>
          {
            tag:'<%= "#{i}"%>' ,
          },        
      <%end%>
    ]
  });
  $('.chips').on('chip.add', function(e, chip){
    var b = document.getElementById("tag_name").value
    b = b +","+ chip["tag"];
    document.getElementById("tag_name").value = b;
  });
  $('.chips').on('chip.delete', function(e, chip){
    var b = chip["tag"]
    var c = document.getElementById("tag_name").value;
    var length = c.length;
    var a = c.indexOf(b);
    b = c.substr(0,a) + c.substr(a + b.length+1,length)
    document.getElementById("tag_name").value = b;
  });
</script>
<%= link_to 'Show', @video %> | <%= link_to 'Back', videos_path %>
<script>
	document.getElementById("textarea1").value = "<%= @video.description %>";
</script>

app/views/videos/index.html.erb
<p id="notice"><%= notice %></p>

  <div class="row">
    <%@videos.each do |video| %>
    <div class="col s8 m4">   
      <div class="card">
        <%= link_to raw("
          <div class=\"card-image waves-effect waves-block waves-light\">
             #{image_tag(video.preview_images[0])}
          </div>
          <div class=\"card-content\">
            <span class=\"card-title activator grey-text text-darken-4\" style=\" font-size : 15px \">
              <div  style=\"width:100%; white-space:nowrap; overflow:hidden; text-overflow:ellipsis\">
              #{ video.title}
              </div>
            </span>
            More Details
          </div>
        ") , video %>
        </div>
        </div>
    <% end %>
  </div>

app/views/videos/liked.html.erb
<h1>
	LIKED VIDEOS
</h1

app/views/videos/myvideo.html.erb
<p id="notice"><%= notice %></p>
  <div class="row">
    <% @videos.each do |video| %>
    <div class="col s8 m4">   
      <div class="card">
          <div class="card-image waves-effect waves-block waves-light">
             <%= raw("#{image_tag(video.preview_images[0])}")%>
          </div>
          <div class="card-content">
            <span class="card-title activator grey-text text-darken-4" style="font-size : 15px">
              <div style="width:100%; white-space:nowrap; overflow:hidden; text-overflow:ellipsis\">
               <%= "#{ video.title}" %>
              </div>
            </span>
            <%= link_to "View",video_path(video)%> | <%= link_to "Edit",edit_video_path(video)%> | <%= link_to "Delete",video, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
        </div>
    <% end %>
  </div>

app/views/videos/new.html.erb
<h1>New Video</h1>
<%= simple_form_for( @video ,remote: true) do |form| %>
<div class="form-inputs"> 
    <%= form.hidden_field :tag_name, value: "" ,id: :tag_name%>
    <%= form.input :title, id: :video_title %>
    <div class="row">
        <div class="input-field col s12">
          <textarea id="textarea1" name="video[description]" class="materialize-textarea"></textarea>
      <label for="textarea1">Description</label>
        </div>
    </div>
    <label for="spaceTags">Tags</label>
    <div id="spaceTags" class="chips chips-placeholder">
    </div>
    <%= form.label :movie %>
    <%= form.file_field :movie %>
    <%= form.label :preview_images%>
    <%= form.file_field :preview_images, multiple: true %>
    <p>
      <input type="checkbox" name=video[published] id="test5" />
      <label for="test5">Publish Video</label>
    </p>
  <div class="form-actions">
    <%= form.submit%>
  </div>
<% end %>
<script type="text/javascript">
  $('#textarea1').trigger('autoresize');
  $('.chips').material_chip();
  $('.chips-placeholder').material_chip({
    placeholder: 'Enter a tag',
    secondaryPlaceholder: '+Tag',
    autocompleteOptions: {
      data: <%= raw(@taghashj) %>,
      limit: Infinity,
      minLength: 1
    }
  });
  $('.chips').on('chip.add', function(e, chip){
    var b = document.getElementById("tag_name").value
    b = b +","+ chip["tag"];
    document.getElementById("tag_name").value = b;
    });

  $('.chips').on('chip.delete', function(e, chip){
    var b = chip["tag"]
    var c = document.getElementById("tag_name").value;
    var length = c.length;
    var a = c.indexOf(b);
    alert(a);
    alert(b);
    alert(c.substr(0,a));
    alert(c.substr(a + b.length + 1 ,length));
    b = c.substr(0,a) + c.substr(a + b.length+1,length)
    alert(b);
    document.getElementById("tag_name").value = b;
  });
</script>

app/views/videos/show.html.erb
<br>
<video class="responsive-video" controls style="width:100%" onclick="viewed();" id="display" onload="myFunction()">
    <source src=<%= @video.movie %> >
</video>
<a class="btn-floating btn-large waves-effect waves-light red"><i class="material-icons">add</i></a>
<p>
  <strong>Tags:</strong>
  <% for i in @video.tags %>
    @<%=i.name %>
  <%end %>
</p>

<p>
  <strong>Title:</strong>
  <%= @video.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @video.description %>
</p>

<p>
  <strong>Uploader:</strong>
  <%= [@video.uploader.first_name,@video.uploader.last_name].join(" ") %>
</p>

<p>
  <strong>Published:</strong>
  <%= @video.published %>
</p>
<p>
  <strong>No. of Views:</strong>
  <%= number_to_human(@video.count) %>
</p>
<p>
  <strong>No. of Likes:</strong>
  <%= number_to_human(@likes)%>
</p>

<p>
<strong>No. of Dislkes:</strong>
  <%= number_to_human(@dislikes)%>
</p>
<%= render 'comment'%>
<script type="text/javascript">
  function viewed(){
    <% c = Video.find(params[:id]) 
        b= c.count%>
    <% if b.nil? 
        b = 0 
      end%>
    <% b = b+1 %>
    <% c.count = b %>
    <% c.save%>
  }
</script>
<script type="text/javascript">
  function myFunction(){
  <%if @video.preview_images[0].nil?%>
     var $pop = Popcorn("#display"),
      poster;
     poster = $pop.currentTime(10).capture();
  <% else %>
    document.getElementById("display-video").poster = '<%= @video.preview_images[0] %>';
  <%end%>
  }
</script>